### ISSUE TITLE
Two factor authentication

### ISSUE THREAD

**Issue by cpipero** [Jake0303/RobinHood-RSI-Trading-Bot#1]
I was looking into getting around the 2FA prompt (which prevents me to automate the startup).
But I think this pyrh issue has a good answer https://github.com/robinhood-unofficial/pyrh/issues/221 .

Probably worth mentioning.

This is great work, thanks! 

Cos

**Comment by cpipero** [comment]
I updated my VisualStudio solution to fetch the master instead of the pip default (by asking for `git+https://github.com/robinhood-unofficial/pyrh.git#egg=pyrh` in the Python Packages Manager).

Unfortunately, they changed the API. So the login parameters are now in the constructor, I had to change the code as follows:
```python
...
#A Simple Robinhood Python Trading Bot using RSI (buy <=30 and sell >=70 RSI) and with support and resistance.
#Youtube : Jacob Amaral
# Log in to Robinhood app (will prompt for two-factor)
rh = Robinhood("username", "password")
# rh.login(username="user@mail.com", password="H@rd2Crack")
#Setup our variables, we haven't entered a trade yet and our RSI period
enteredTrade = False
...
```

And that works, but then other functions have changed so I get the following output:

```
Getting historical quotes
Input challenge code from Email (3/3):
537813
Invalid code entered
Input challenge code from Email (3/3):
567813
Current Support is :
6.165
Current Resistance is :
6.165
Current Resistance is :
6.175
Current Support is :
6.16
Traceback (most recent call last):
  File "RobinhoodBot.py", line 64, in <module>
    s.run()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\sched.py", line 151, in run
    action(*argument, **kwargs)
  File "RobinhoodBot.py", line 48, in run
    instrument = rh.instruments("F")[0]
TypeError: 'generator' object is not subscriptable
```

It's going to take me a while to troubleshoot.

Any help and advice welcome.

**Comment by HaxOh** [comment]
Getting strange RSI results. This is on AMD 5 min candles on 7/28/2020. The RSI on Robinhood web and ToS are staying pretty close to 50. Getting wild swings from the bot though, from 0-29. Support and Resistance look to be working `correctly.`

`Getting historical quotes
Current Support is : 
69.58
Current Resistance is : 
69.58
Current Resistance is : 
69.65
Current Support is : 
69.475
Current Support is : 
69.245
Current Support is : 
69.175
Buying RSI is below 30!
[14.7826087]
Getting historical quotes
Current Support is : 
69.63
Current Resistance is : 
69.63
Current Support is : 
69.475
Current Support is : 
69.2967
Current Support is : 
69.26
Current Support is : 
69.175
Current Support is : 
69.12
[0.]
Getting historical quotes
Current Support is : 
69.475
Current Resistance is : 
69.475
Current Support is : 
69.245
Current Support is : 
69.175
Current Support is : 
69.12
Resetting support and resistance
Current Support is : 
69.09
Current Resistance is : 
69.09
[3.61445783]
Getting historical quotes
Current Support is : 
69.245
Current Resistance is : 
69.245
Current Resistance is : 
69.26
Current Support is : 
69.175
Current Support is : 
69.07
Resetting support and resistance
Current Support is : 
69.09
Current Resistance is : 
69.09
Current Support is : 
69.06
[13.7254902]
Getting historical quotes
Current Support is : 
69.26
Current Resistance is : 
69.26
Current Support is : 
69.175
Current Support is : 
69.07
Resetting support and resistance
Current Support is : 
69.09
Current Resistance is : 
69.09
Current Support is : 
69.06
Current Support is : 
69.03
[7.40740741]
Getting historical quotes
Current Support is : 
69.175
Current Resistance is : 
69.175
Current Support is : 
69.12
Resetting support and resistance
Current Support is : 
69.09
Current Resistance is : 
69.09
Current Support is : 
69.06
Current Support is : 
69.03
Current Support is : 
68.9166
[0.]
Getting historical quotes
Current Support is : 
69.12
Current Resistance is : 
69.12
Resetting support and resistance
Current Support is : 
69.09
Current Resistance is : 
69.09
Current Support is : 
69.06
Current Support is : 
69.03
Current Support is : 
68.9166
[29.07949791]`

**Comment by Jake0303** [comment]
Just a heads up your username and password are in your quote, I would remove it ASAP.

**Comment by danoc505** [comment]
has there been any solutions to this? The code is being sent to me via txt and when I put it back into the command line it brings up an error. Is there a way to store it in the bots code like the user name?
